name: flutter_jkxing
description: 健客行

version: 2.6.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  dio: ^2.1.16
  json_annotation: ^3.0.0
  device_info: ^0.4.0+2
  shared_preferences: ^0.5.3+4

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.2
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lib/Images/login_icon_account.png
    - lib/Images/login_icon_jkx.png
    - lib/Images/login_icon_logo.png
    - lib/Images/login_icon_password.png
    - lib/Images/login_icon_safe.png
    - lib/Images/tab_drug_lib.png
    - lib/Images/tab_drug_lib_sel.png
    - lib/Images/tab_home.png
    - lib/Images/tab_home_sel.png
    - lib/Images/tab_mine.png
    - lib/Images/tab_mine_sel.png
    - lib/Images/tab_order.png
    - lib/Images/tab_order_sel.png
    - lib/Images/tab_pre.png
    - lib/Images/tab_pre_sel.png
    - lib/Images/rx_flag.png
    - lib/Images/rx_label_flag.png
    - lib/Images/img_default_medicine.png
    - lib/Images/img_pharmacy_mytj.png
