name: flutter_jkxing
description: 健客行

version: 2.6.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  dio: ^2.1.16
  json_annotation: ^3.0.0
  device_info: ^0.4.0+2
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.3
  extended_nested_scroll_view: ^0.3.7
  webview_flutter: ^0.3.15+1
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  flutter_easyrefresh:
    git: git://github.com/xuelongqy/flutter_easyrefresh.git

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lib/Images/login_icon_account.png
    - lib/Images/login_icon_jkx.png
    - lib/Images/login_icon_logo.png
    - lib/Images/login_icon_password.png
    - lib/Images/login_icon_safe.png
    - lib/Images/tab_drug_lib.png
    - lib/Images/tab_drug_lib_sel.png
    - lib/Images/tab_home.png
    - lib/Images/tab_home_sel.png
    - lib/Images/tab_mine.png
    - lib/Images/tab_mine_sel.png
    - lib/Images/tab_order.png
    - lib/Images/tab_order_sel.png
    - lib/Images/tab_pre.png
    - lib/Images/tab_pre_sel.png
    - lib/Images/rx_flag.png
    - lib/Images/rx_label_flag.png
    - lib/Images/img_default_medicine.png
    - lib/Images/img_pharmacy_mytj.png
    - lib/Images/img_invite_volet.png
    - lib/Images/img_invite_n0_network.png
    - lib/Images/icon_invite_wechat.png
    - lib/Images/share_btn_moments.png
    - lib/Images/share_btn_wechat.png
    - lib/Images/btn_arrow.png
    - lib/Images/date_icon_dropdown.png
    - lib/Images/home_btn_more.png
    - lib/Images/nav_btn_back.png
    - lib/Images/me_btn_msg.png
    - lib/Images/mini_right_arrow.png
    - lib/Images/btn_date_unselect.png
    - lib/Images/btn_date_select.png
    - lib/Images/login_token_failed.png
    - lib/Images/login_token_loading.png
    - lib/Images/order_detail_line.png
    - lib/Images/loading.gif
    - lib/Images/net_error_img.png


